apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nikappdb
  name: nikappdb
  namespace: nikdeploy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikappdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nikappdb
    spec:
      volumes:
      - name: nikdbvol
        hostPath:
          path: /data/nikdb
          type: DirectoryOrCreate
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: nikappdb-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nikappdb-sec
              key: db_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nikappdb-sec
              key: root_pass
        resources: {}
        volumeMounts:
        - name: nikdbvol
          mountPath: /var/lib/mysql
status: {}
