apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nikappdb-svc
  name: nikappdb-svc
  namespace: nikdeploy-ns
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: nikappdb
  type: ClusterIP
status:
  loadBalancer: {}
