apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nikappweb
  name: nikappweb
  namespace: nikdeploy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikappweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nikappweb
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
           name: nikappweb-config
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: nikappdb-sec
                key: db_pass
        resources: {}
status: {}
