apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nikappweb-svc
  name: nikappweb-svc
  namespace: nikdeploy-ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
    nodePort: 30101
  selector:
    app: nikappweb
  type: NodePort
status:
  loadBalancer: {}
